-- 加急单结算报告
select
Id `表ID`,
TransactionType `交易类型`,
left(`SettlementTime`,7)  "结算月份",
case when TransactionType='其他' and left(SellerSku,10)='ProductAds' then TotalExpend end  `其他类型对应扣除店铺费用`,
`SettlementTime`  "结算时间",
`PayTime` "付款时间",
OrderNumber `系统订单号`,
`PlatOrderNumber`"平台订单号",
`OrderStatus` "订单状态",

wo.`BoxSku` "塞盒系统SKU",
-- tb.person `商厨汇运营人员`,
Product_Name  `产品名称`,
`SellerSku`  "渠道SKU",
`Asin`,
`shopcode`"店铺",
ms.nodepathname `销售小组`,
  `SalePlatform` "销售平台",
  `OrderCountry`  "订单国家",
--   case when ShipWarehouse regexp 'FBA' then 'FBA模式' else 'FBM模式' end `发货方式`,
  `ShipWarehouse` "发货仓库",
  `TransportType`  "运输方式",
  `ShipMethod` "发货方式",
--   `GroupSku` "组合SKU",
--   `GroupSkuNumber` "组合SKU数量",
  --   `Currency` "订单币种",
  `TotalGross` "总收入",
  `TotalProfit`  "总利润",
  `TotalExpend` "总支出",
  `SaleCount` "销售数量",
  `SalePrice` "产品售价",
  `ModifyCount` "修改数量",
  `OrderTotalPrice`  "订单总金额（原币）",
   `ExchangeRMB`  "原币对人民币汇率",
  `ExchangeUSD` "美元对人民币汇率",
  `FeePrice`  "运费",
  `SalesGross`  "销售收入",
  `FeeGross`  "运费收入",
  `RefundAmount`  "退款金额",
  `PromotionalDiscounts`  "促销折扣",
  `OtherGross` "其他收入",
  `TradeCommissions`  "交易佣金",
  `FBAFee`  "FBA操作费",
  `OtherExpend`  "平台其他支出",
  `AdvertisingCosts` "广告费用",
  `PurchaseCosts`  "采购成本",
  `LocalFreight` "本地仓运费",
  `OverseasDeliveryFee` "海外仓派送运费",
  `HeadFreight`  "头程运费",
  `RateDiscount` "汇率折损",
  `PackageCosts`  "包装成本",
  `SubsidyAdjustment`  "补贴调整",
  `SellVat`  "销售VAT",
  `WarehouseCosts`  "仓库管理成本（自定义费用项）",
  `OtherExpenseCosts`  "其它费用成本（自定义费用项）",
  `TaxGross`  "税费收入",
  `DeductTaxes`  "扣除客户支付税费",
  `ManualImportCharges`  "人工导入费用",
  `memo`  "客户备注"
from import_data.wt_orderdetails wo
join mysql_store ms on wo.shopcode = ms.Code and ms.Department = '快百货'
where SettlementTime >= '2023-04-01' and SettlementTime <= '2023-07-31' and IsDeleted = 0
    and PlatOrderNumber in (select distinct PlatOrderNumber from  import_data.wt_orderdetails wo
        join mysql_store ms on wo.shopcode = ms.Code and ms.Department = '快百货'
        where SettlementTime >= '2023-04-01' and SettlementTime <= '2023-07-31' and IsDeleted = 0 and wo.FeeGross >0 )

-- 物流轨迹追踪
select
    OrderNumber                 '订单号',
    PlatOrderNumber             '平台订单号',
    PackageNumber               '包裹号',
    TransportType               '物流方式',
TransportUseType                '物流追踪方式:追踪号,1:物流单号',
TransportBoxId                  '物流方式赛盒',
    LogisticsNumber             '物流单号',
    TraceNo                     '追踪号',
    RealTrackNo                 '物流追踪号',
    ServiceType                 '服务代码',
    ShippingCountry             '发货国家',
    RecipientCountry            '收货国家',
    IsRegister                      '是否已经注册到轨迹',
    RegisterTime                   '注册到轨迹的时间',
    OnlineTime                     '第一次上网时间',
    IsTracking                      '是否已经追踪',
    SystemTrackingTime             '奈思系统追踪的时间',
    DeliverTime                    '妥投时间',
    TrackingStatus                  '轨迹状态:查询不到,1:待上网,:运输途中,3:运输过久,4:到达待取,5:派送途中,6:投递失败,7:成功签收,8:可能异常,-1:全部',
    IsFinish                        '是否流程已经完毕',
    ShopCode                    '店铺简码',
    OnLineHour                       '上网时间小时',
    DeliverHour                      '妥投小时',
    AvailableForPickupTime         '到达待取时间',
    SiteCode                 '站点',
    MerchantId                     '物流商ID',
    MerchantName               '物流商名称',
    OrderTime                      '下单时间',
    PackageStatus               '包裹状态',
    RecipientCountryCnName      '收货国家中文名称',
    ShippingCountryCnName       '发货国家中文名称',
    WareHouseName              '发货仓库',
    WeightTime                     '称重发货时间',
    ServiceCode                '追踪服务Code',
    WareHouseId                    '仓库Id',
    Remark                    '备注内容',
    TrackRemarkId                  '备注类型'
from erp_logistic_logistics_tracking
where PlatOrderNumber in (select distinct PlatOrderNumber from  import_data.wt_orderdetails wo
        join mysql_store ms on wo.shopcode = ms.Code and ms.Department = '快百货'
        where SettlementTime >= '2023-04-01' and SettlementTime <= '2023-07-31' and IsDeleted = 0 and wo.FeeGross >0 )